import socket
import logging

class AdbSocketMultiplexer:
    """
    Bypasses the standard 'adb' terminal binary.
    Communicates directly with the ADB Daemon (port 5037) via low-level raw TCP sockets.
    Achieves microsecond-level execution latency for UI automation, gaming, and rapid commands.
    """
    def __init__(self, host="127.0.0.1", port=5037):
        self.host = host
        self.port = port
        self.logger = logging.getLogger(__name__)

    def _create_socket(self):
        """Creates a raw TCP socket to the internal Mac ADB daemon."""
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        
        # ⚡ Disable Nagle's algorithm (TCP_NODELAY) to mathematically eliminate network buffering
        s.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
        
        s.connect((self.host, self.port))
        return s

    def _send_command(self, sock, command):
        """Formats the command into the precise 4-byte hex prefix required by the ADB Protocol."""
        length_prefix = f"{len(command):04x}"
        payload = f"{length_prefix}{command}".encode('utf-8')
        sock.sendall(payload)
        
        # The ADB Daemon responds with 4 bytes: either "OKAY" or "FAIL"
        status = sock.recv(4).decode('utf-8')
        if status != "OKAY":
            error_len_str = sock.recv(4).decode('utf-8')
            if error_len_str:
                error_len = int(error_len_str, 16)
                error_msg = sock.recv(error_len).decode('utf-8')
                raise RuntimeError(f"ADB Protocol Rejected: {error_msg}")
            raise RuntimeError("ADB Protocol Rejected: Unknown Error")

    def execute_instant_shell(self, device_serial: str, shell_command: str) -> str:
        """
        Executes a shell command without spawning a heavy macOS subprocess.
        Ideal for firing sub-millisecond click/swipe events generated by the AI Ghost Driver.
        """
        try:
            sock = self._create_socket()
            
            # Step 1: Target the specific Android device
            self._send_command(sock, f"host:transport:{device_serial}")
            
            # Step 2: Inject the shell command at wire-speed
            self._send_command(sock, f"shell:{shell_command}")
            
            # Step 3: Stream back the response
            output = b""
            while True:
                chunk = sock.recv(4096)
                if not chunk:
                    break
                output += chunk
                
            sock.close()
            return output.decode('utf-8', errors='ignore')
            
        except Exception as e:
            self.logger.error(f"Raw Socket execution failed: {e}")
            return ""
