import socket
import logging

class AdbSocketMultiplexer:
    """
    Bypasses the standard 'adb' terminal binary.
    Communicates directly with the ADB Daemon (port 5037) via low-level raw TCP sockets.
    Achieves microsecond-level execution latency for UI automation, gaming, and rapid commands.
    """
    def __init__(self, host="127.0.0.1", port=5037, timeout=5.0, max_output=8 * 1024 * 1024):
        self.host = host
        self.port = port
        self.timeout = float(timeout)
        self.max_output = int(max_output)
        self.logger = logging.getLogger(__name__)

    def _create_socket(self):
        """Creates a raw TCP socket to the internal Mac ADB daemon."""
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(self.timeout)
        
        # ⚡ Disable Nagle's algorithm (TCP_NODELAY) to mathematically eliminate network buffering
        s.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
        
        s.connect((self.host, self.port))
        return s

    @staticmethod
    def _recv_exact(sock, length):
        chunks = []
        remaining = length
        while remaining:
            chunk = sock.recv(remaining)
            if not chunk:
                raise ConnectionError("ADB daemon closed the socket unexpectedly")
            chunks.append(chunk)
            remaining -= len(chunk)
        return b"".join(chunks)

    def _send_command(self, sock, command):
        """Formats the command into the precise 4-byte hex prefix required by the ADB Protocol."""
        command_bytes = command.encode("utf-8")
        if len(command_bytes) > 0xFFFF:
            raise ValueError("ADB command is too large")
        payload = f"{len(command_bytes):04x}".encode("ascii") + command_bytes
        sock.sendall(payload)
        
        # The ADB Daemon responds with 4 bytes: either "OKAY" or "FAIL"
        status = self._recv_exact(sock, 4).decode('ascii', errors='replace')
        if status != "OKAY":
            error_len_str = self._recv_exact(sock, 4).decode('ascii', errors='replace')
            if error_len_str:
                try:
                    error_len = int(error_len_str, 16)
                except ValueError as exc:
                    raise RuntimeError(f"Invalid ADB failure frame: {error_len_str!r}") from exc
                if error_len > 1024 * 1024:
                    raise RuntimeError("ADB failure response exceeded safety limit")
                error_msg = self._recv_exact(sock, error_len).decode('utf-8', errors='replace')
                raise RuntimeError(f"ADB Protocol Rejected: {error_msg}")
            raise RuntimeError("ADB Protocol Rejected: Unknown Error")

    def execute_instant_shell(self, device_serial: str, shell_command: str) -> str:
        """
        Executes a shell command without spawning a heavy macOS subprocess.
        Ideal for firing sub-millisecond click/swipe events generated by the AI Ghost Driver.
        """
        try:
            with self._create_socket() as sock:
            
            # Step 1: Target the specific Android device
                self._send_command(sock, f"host:transport:{device_serial}")
            
            # Step 2: Inject the shell command at wire-speed
                self._send_command(sock, f"shell:{shell_command}")
            
            # Step 3: Stream back the response
                output = bytearray()
                while True:
                    chunk = sock.recv(65536)
                    if not chunk:
                        break
                    output.extend(chunk)
                    if len(output) > self.max_output:
                        raise RuntimeError("ADB shell output exceeded safety limit")
            return output.decode('utf-8', errors='ignore')
            
        except Exception as e:
            self.logger.error("Raw ADB socket execution failed: %s", e)
            raise
